name: code coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix: 
        changed_modules: [mod1, mod2]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get module
      run: |
          echo "${{ matrix.changed_modules }}"
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -X clean test install jacoco:report

      # Runs a set of commands using the runners shell
      
    - name: Run a multi-line script
      run: |
          echo setup token
          export CODACY_PROJECT_TOKEN=a9d3fdfb91534f119d608e1d8d54b40b
          echo run upload command
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java $(find **/jacoco*.xml -printf '-r %p ')
          echo report command execution complete
          echo "${{ github.event.pull_request.base.sha }}"
          echo "${{ github.sha }}"
          echo "--------------------"
          echo "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d/ -f1 | sort -u )"
